name: Release Charts
on:
   push:
     branches:
       - main
jobs:
   release:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2
         with:
           fetch-depth: 0

       - name: Setup Python
         uses: actions/setup-python@v5.2.0

       - name: Configure Git
         run: |
           git config user.name "$GITHUB_ACTOR"
           git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

       - uses: azure/setup-helm@v4
         with:
            token: ${{ secrets.GITHUB_TOKEN }}

       - name: Set up Bitnami chart (for dependencies)
         run: |
            helm repo add bitnami https://charts.bitnami.com/bitnami

       - name: Helm Lint
         run: |
           cd .github/workflows/
           ./helm_lint.sh

       - name: Create k8s Kind Cluster
         uses: helm/kind-action@v1.5.0
         
       - name: Install kubectl
         uses: Azure/setup-kubectl@v3
         
       - name: Deploy all charts to kind
         run: |
           cd .github/workflows/
           ./helm_deploy.sh

       - name: Run chart-releaser
         uses: helm/chart-releaser-action@v1.5.0
         env:
           CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
           
       - name: Modifying the readme on main
         continue-on-error: true
         run: |
          git pull
          git checkout main
          cd .github/workflows/
          python -m pip install -r requirements.txt 
          python3 get_readme.py
          cd ../..
          git add README.md
          git commit -m ":lock: Auto-Update README with Charts versions"
          git push
          
       - name: Setup Pandoc
         uses: nikeee/setup-pandoc@v1
         
       - name: Modifying index.html
         continue-on-error: true
         run: |
          index=$(pandoc --from gfm README.md --to html5 --standalone --toc --citeproc --no-highlight)
          git checkout gh-pages
          echo $index > index.html
          echo '<script defer data-domain="qjoly.github.io/helm-charts" src="https://stats.192168128.xyz/js/plausible.js"></script>' >> index.html
          git add index.html
          git commit -m "[AUTO] Update index.html of gh-pages"
          git push
        